//
//  FilmData.swift
//  Moodie
//
//  Created by Dominick Ferraro on 09/04/21.
//  Copyright © 2021 Duy Bui. All rights reserved.
//

import Foundation

struct Film {
    var titolo:String
    var descrizione:String
    var locandina:String
    
}

var arrayPositivi = [Film (titolo: "The pursuit of happiness", descrizione: "The title of this feel-good film says it all. Prepare to be inspired to chase your dreams! ", locandina: "thepursuitofhappyness"),
                     Film (titolo: "Because I said so", descrizione: "Anyone with a meddling mom will relate to this movie about what happens when a mother tries to get involved in her daughter's dating life. Naturally, the outcome is hilarious—and very heartwarming.", locandina: "becauseisaidso"),
                     Film (titolo: "Forrest Gump", descrizione: "It's impossible not to feel inspired by the childlike optimism that guides Forrest through his life. Plus, you'll enjoy plenty of laughs along the way!", locandina: "forrestgump"),
                     Film (titolo: "Pitch Perfect", descrizione: "This outrageous, star-studded comedy will have you singing in the shower for days after the credits roll.", locandina: "pitchperfect"),
                     Film (titolo: "Matilda ", descrizione: "Matilda is an ordinary girl with a fairy-tale talent, and her exciting adventures teach a powerful lesson.", locandina: "matilda"),
                     Film (titolo: "Just go with it ", descrizione: "This hilarious rom-com shows what happens when a man fakes a family to avoid commitment—but ends up finding true love anyway.", locandina: "justgowithit"),
                     Film (titolo: "13 going on 30", descrizione: "Adults and kids alike will fall in love with this coming-of-age tale about a young teenager who learns the hard way what it's really like to grow up. ", locandina: "13goingon30"),
                     Film (titolo: "Love actually", descrizione: "Whether you're gearing up for the holidays or relaxing on summer vacation, there's never a bad time to watch this charming classic. ", locandina: "love actually"),
                     Film (titolo: "Zootopia ", descrizione: "Officer Judy Hopps is determined to crack a case in the all-animal city of Zootopia—even if it means partnering with a sly criminal. ", locandina: "zootopia "),
                     Film (titolo: "Frozen", descrizione: "There's a reason kids and adults are equally obsessed with this Disney cartoon. Make like Elsa and 'let it go!' ", locandina: "frozen"),
                     Film (titolo: "Ferris Bueller's Day Off", descrizione: "Revisit your teenage years and watch this John Hughes film while playing hooky from work. Just make sure your boss doesn't catch you!", locandina: "Ferris_Bueller's_Day_Off"),
                     Film (titolo: "The Blind Side", descrizione: "Real-life stories of sports heroes always leave you feeling like you can accomplish anything, and The Blind Side is no exception. ", locandina: "theblindside"),
                     Film (titolo: "Along come Polly", descrizione: "Reuben has always played it safe—until Polly came along. Prepare to LOL as you watch him try to keep up with her crazy antics! ", locandina: "alongcomepolly_"),
                     Film (titolo: "Mrs.Doubtfire", descrizione: "An eccentric father poses as Mrs. Doubtfire, a beloved British nanny, for a chance to spend more time with his kids. His plan ultimately gets derailed—but maybe it's for the best. ", locandina: "Mrs_Doubtfire"),
                     Film (titolo: "The Parent Trap", descrizione: "Double the daughters, double the smiles. Find out what happens when identical twins switch places and trick their parents. ", locandina: "the parent trap"),
                     Film (titolo: "Grease ", descrizione: "This movie is the one that you want! Every line and lyric in this 1978 classic is more quotable than the next—so prepare to sing along. ", locandina: "locandina_grease"),
                     Film (titolo: "Wall-E", descrizione: "WALL-E, short for Waste Allocation Load Lifter Earth-class, is the last robot left on the planet. That is, until he meets EVE—and his whole life changes. ", locandina: "walle"),
                     Film (titolo: "Wedding Crashers ", descrizione: "Leave it to a couple of lonely divorce attorneys to figure out a systematic way to pick up women at weddings. They have it down to a science—until they actually fall in love.", locandina: "weddingcrashers"),
                     Film (titolo: "The bucket list ", descrizione: "Leave it to a couple of lonely divorce attorneys to figure out a systematic way to pick up women at weddings. They have it down to a science—until they actually fall in love. ", locandina: "bucketlist"),
                     Film (titolo: "Good will hunting", descrizione: "A young man with a gift for mathematics can solve any equation, but can't figure out the direction of his own life. Then he meets an unorthodox psychologist who changes everything. ", locandina: "goodwillhunting"),
                     Film (titolo: "The Help", descrizione: "While this novel-based movie tackles the heavy topics of racism and segregation, the main characters will bring you nothing but smiles. ", locandina: "thehelp"),
                     Film (titolo: "Mamma Mia !", descrizione: "Have the time of your life watching this all-star cast act out a celebration of family, friends, and love.", locandina: "mammamia"),
                     Film (titolo: "Legally Blonde ", descrizione: "lle Woods will teach you how to 'bend and snap,' but more importantly, she'll remind you to never judge a book by its (pink) cover. ", locandina: "legallyblonde"),
                     Film (titolo: "Little miss sunshine", descrizione: "A quirky family with plenty of love to give takes a cross-country road trip and learns a lot about each other along the way. ", locandina: "littlemisssunshine"),
                     Film (titolo: "The proposal ", descrizione: "When a high-powered book editor faces deportation, she calls upon her assistant for help...in the form of getting married. ", locandina: "The_Proposal"),
                     Film (titolo: "Ratatouille", descrizione: "One of Pixar's most charming entries, this food-focused tale is like a warm (and delicious) hug.", locandina: "ratatouille"),
                     
                     Film (titolo: "The devil wears Prada ", descrizione: "A rare film that surpasses the quality of its source novel, this Devil is a witty expose of New York's fashion scene, with Meryl Streep in top form and Anne Hathaway more than holding her own.", locandina: "thedevilwearsprada"),
                     Film (titolo: "Catch me if you can", descrizione: "With help from a strong performance by Leonardo DiCaprio as real-life wunderkind con artist Frank Abagnale, Steven Spielberg crafts a film that's stylish, breezily entertaining, and surprisingly sweet.", locandina: "catch me if you can"),
                     Film (titolo: "About a boy", descrizione: "About a Boy benefits tremendously from Hugh Grant's layered performance, as well as a funny, moving story that tugs at the heartstrings without tilting into treacle.", locandina: "aboutaboy"),
                     Film (titolo: "A nightmare on Elm Street ", descrizione: "Just like a certain dungaree-clad possessed doll, Freddy Krueger fell firmly into killer clown territory as the Nightmare on Elm Street franchise evolved over the years. Sure, he’ll spray your organs all over the walls but you’ll die laughing, right? Look back at Wes Craven’s original movie, though, and Freddy isn’t to be trifled with. Our selective memories mean we often forget that this serial child killer’s burns come from him being incinerated by an angry mob of parents. Living eternally through their fear and guilt, Freddy becomes the ultimate boogeyman when he dons his favourite murder glove and goes after a whole new generation of Springwood spawn while they slumber.   ", locandina: "anightmareonelmstreet"), // 7
                     Film (titolo: "Evil Dead 2", descrizione: "So many Evil Dead 2 questions, so little time. Is it a remake? Is it a sequel? Would it actually be physically possible to switch out your missing (presumed possessed) hand for a chainsaw with relative ease? Well, thankfully, Bruce Campbell himself has answered the first two and explained that Sam Raimi’s cabin-based comedy horror is, in fact, a ‘requel.’ Whereas the original Evil Dead followed a group of twenty somethings to a holiday house from hell, the sequel revolves exclusively around Campbell’s Ash and his girlfriend Linda as they attempt to survive after playing a reading of the Necronomicon aloud. I'd be remiss if I didn't warn you about someone being beheaded with a garden tool post reading.", locandina: "evildead2"),
                     Film (titolo: "The Babadook", descrizione: "So many Evil Dead 2 questions, so little time. Is it a remake? Is it a sequel? Would it actually be physically possible to switch out your missing (presumed possessed) hand for a chainsaw with relative ease? Well, thankfully, Bruce Campbell himself has answered the first two and explained that Sam Raimi’s cabin-based comedy horror is, in fact, a ‘requel.’ Whereas the original Evil Dead followed a group of twenty somethings to a holiday house from hell, the sequel revolves exclusively around Campbell’s Ash and his girlfriend Linda as they attempt to survive after playing a reading of the Necronomicon aloud. I'd be remiss if I didn't warn you about someone being beheaded with a garden tool post reading.", locandina: "thebabadook"),
                     Film (titolo: "The cabina in the woods", descrizione: "By 2011, we were having a self-referential horror crisis. Scream 4 was out and had an intro multiple layers deep, smashing the fourth wall into pieces with horror-ception as character after character quipped about the masked slasher genre. But where could comedy horror go next? How many times could a leading actress say “I saw this in a movie once” without us wanting to remove our own eyes and never watch horror again? Well, it turns out that there was still some life in the reanimated corpse yet. The Cabin in the Woods manages to pin not just one horror trope but every single one, like someone armed with a laser sight and Final Destination 3’s nail gun. When this lot of attractive twenty-somethings head to the titular spot, they get significantly more than they bargained for. Oh, and Chris Hemsworth is one of them. Now you’re interested…  ", locandina: "thecabininthewoods"),
                     Film (titolo: "A quiet place", descrizione: "Is there anything more terrifying than the idea of bringing up a young family in a world where brutal monstrosities with supernaturally good hearing hunt down the last of humanity? John Krasinski’s first horror - in which he also stars with IRL wife Emily Blunt - follows the Abbott family as they silently creep through a truly miserable existence where every single sound could be their last. Playing with movie audio in an entirely new way, A Quiet Place might have a simple premise but this is 90 minutes of sheer muscle-clenching tension. ", locandina: "aquietpalce"),
                     Film (titolo: "Paranormal Activity", descrizione: "While The Blair Witch Project revved found footage horror back into action like a haunted motorbike back in 1999, Paranormal Activity is where things got, err, dead serious. The first movie from now horror staple Oren Peli, it introduces us to Katie and Micah who have been experiencing some odd goings on in their LA home. Ever the keen filmmaker, Micah sets up a camera at the foot of their bed to keep an eye on things while they sleep. The bumps in the night that follow are enough to make you never want to see another bed again, let alone lie on one.    ", locandina: "paranormalactivity"),
                     Film (titolo: "Suspiria", descrizione: "Less a movie and more an assault on your senses, not to mention your stomach, Dario Argento’s Suspiria follows young dancer Suzy as she arrives at a famous ballet school. Unfortunately, she doesn’t heed the girl running in the other direction and finds herself surrounded by horrific murder as young women are picked off artfully one by one. Still a gory cut above the remake, Argento’s original faced multiple cuts around violence on release and was one of the films at the bloody centre of the 1980s video nasty panic. It doesn’t take long to see why.    ", locandina: "suspiria"),
                     Film (titolo: "The Descent", descrizione: "If there was a dip in caving and bouldering trip attendance back in the mid-noughties, it’s probably the fault of Neil Marshall’s truly terrifying claustrophobic creature feature. Sarah’s friends want to make her feel better after the tragic death of her family so, instead of y’know, buying her some gin, they take her on a caving trip. Unfortunately, the movie wouldn’t be on this list if the six women were there to have a heartwarming, gently comedic adventure where they all grow as people. From the moment this lot lower themselves into the darkness below the Appalachian mountains, it’s very clear that getting back out into the light again isn’t going to be likely.", locandina: "thedescent"),
                     Film (titolo: "The texas chain sai massacre", descrizione: "Some movie titles are vague, letting you gradually work out their meaning as the narrative slowly unfurls in front of your eyes like a delicate flower in tea. Then there’s Tobe Hooper’s grim, sweaty horror movie. There is nothing delicate here. Its titular weapon needs to be sharp but The Texas Chainsaw Massacre is a blunt instrument of horror. This is a tour de force of violence as five young people leave the safety of the world behind and journey into dusty Americana. What they find in one house when they innocently enter looking for gas is such death and depravity that the movie is still, decades on, a disturbing endurance test. ", locandina: "thetexaschaisawmassacre("),
                     Film (titolo: "Eternal Sunshine of the Spotless Mind", descrizione: "Jim Carrey and Kate Winslet star in this metaphysical journey of lost love, which follows the story of a split couple who both undergo a procedure to erase their memories of one another. The film boasts a classically Charlie Kaufman script, though if you’re not one for the Manic Pixie Dream Girl trope, take a pass.", locandina: "eternal sunshine of the spotless mind"),
                     Film (titolo: "BEFORE SUNRISE", descrizione: "The first installment of the Before trilogy, Before Sunrise follows the whimsical romance of a young man and woman who meet on a train and decide to take off for one night in Vienna. A perfect ode to love strained by limits, this film will leave you reeling—and relieved to know there’s more where it came from.", locandina: "before sunrise"),
                     Film (titolo: "Shakespeare in Love", descrizione: "The title says it all. What can be more romantic than a love affair involving famed playwright William Shakespeare at the time he pens the iconic Romeo and Juliet? A forbidden romance and period piece with a side of vintage Gwyneth Paltrow. Thank us later.", locandina: "shakespeare in love"),
                     Film (titolo: "Shape of Water", descrizione: "If you know anything about Guillermo del Toro, then you know better than to ever try to predict what the fantastical director’s take on a love story would be. Besides, of course, that it will be more beautiful and unique than you could ever imagine. Shape of Water tells the tale of Elisa, a mute woman who works as a cleaning lady at a government laboratory, as she finds herself falling in love with the lab’s top-secret specimen: an amphibious creature. This film is a true testament that love comes in all shapes and sizes.", locandina: "shape of water"),
                     Film (titolo: "SLUMDOG MILLIONAIRE", descrizione: "Directed by Danny Boyle, Slumdog Millionaire follows Jamal Malik, from his childhood as an orphan to ending up one question away from winning India’s “Who Wants to Be a Millionaire?” Perhaps the most moving plot point of Malik’s against-all-odds journey is that he lives with the sole determination of one day reuniting with his childhood love, Latika. The film is as visually dazzling as it is emotionally gripping, boasting the incredible feature debut of Dev Patel.", locandina: "slumdog millionaire"),
                     Film (titolo: "TITANIC", descrizione: "It’s hard to top being king of the world. Titanic sets the bar incredibly high for romantic epics. The only issue we have is that there was definitely room on that door, but someone had to sprawl out and get cozy.", locandina: "titanic"),
                     Film (titolo: "THE BIG SICK", descrizione: "Kumail Nanjiani and Emily V. Gordon’s real-life hospital romance turned movie is one of the most original and thoughtful romances in years. In the face of tragedy, an estranged couple grows closer somehow by one of them being in a coma. Also, Holly Hunter is the best mom.", locandina: "the big sick"),
                     Film (titolo: "MOONSTRUCK", descrizione: "Snap out of it! The film that stars Nicholas Cage and Cher helped lock in Cher's long-deserved Oscar. The perfect Italian-American film set in New York, Moonstruck is a late-80s classic.", locandina: "moonstruck"),
                     Film (titolo: "CALL ME BY YOUR NAME", descrizione: " That peach scene is something else. The Luca Guadagnino-directed film perfectly encapsulates the feelings of first love and love lost in a beautiful Italian setting. Bonus points: CMBYN is the rare gay love story where someone doesn’t get beaten or end up with HIV.", locandina: "call me by your name"),
                     Film (titolo: "SILVER LININGS PLAYBOOK", descrizione: "The first real entry of the Cooper/Lawrence film trio, Silver Linings Playbook is the story of what happens when perfectly flawed people find love together. The film also won Lawrence her first Oscar, and that’s pretty outstanding for a picture loosely categorized as a romantic comedy.", locandina: "silver"),
                     Film (titolo: "DIRTY DANCING", descrizione: "Young love set in the Catskills, perfectly punctuated with an iconic '80s movie dance lift? Romance gold.", locandina: "dirty dancing"),
                     Film (titolo: "Elizabethtown", descrizione: "Is quirky and cosmetically indie, but it’s still a sweetly thoughtful romance wrapped up in existentialism. Orlando Bloom is the perfect working guy finding his roots again and Kirsten Dunst is nothing if not the poster child for Manic Pixie Dream Girls.", locandina: "elizabethtown"),
                     Film (titolo: "Love & Basketball", descrizione: "Is one of the ultimate sports movies. It just so happens to also be one of the ultimate romances, too. As two friends start establishing themselves as true basketball stars, they fall for each other—but their respective careers may keep them apart.", locandina: "love & basketball"),
                     Film (titolo: "THE BODYGUARDS", descrizione: "Love & Basketball is one of the ultimate sports movies. It just so happens to also be one of the ultimate romances, too. As two friends start establishing themselves as true basketball stars, they fall for each other—but their respective careers may keep them apart.", locandina: "bodyg"),
                   /* Film (titolo: "CAROL", descrizione: "Who doesn’t love a lesbian love story adorned with mid-century forbidden temptation and department store customer service that can’t be beat?!", locandina: "carol"),
                     Film (titolo: "dd", descrizione: "e", locandina: "locandina"),
                     Film (titolo: "dd", descrizione: "e", locandina: "locandina"),
                     Film (titolo: "dd", descrizione: "e", locandina: "locandina"),
                     Film (titolo: "dd", descrizione: "e", locandina: "locandina"),
                     Film (titolo: "dd", descrizione: "e", locandina: "locandina"),
                     Film (titolo: "dd", descrizione: "e", locandina: "locandina"),
                     Film (titolo: "dd", descrizione: "e", locandina: "locandina"),
                     Film (titolo: "dd", descrizione: "e", locandina: "locandina"),
                     Film (titolo: "dd", descrizione: "e", locandina: "locandina"),
                     Film (titolo: "dd", descrizione: "e", locandina: "locandina"),
                     Film (titolo: "dd", descrizione: "e", locandina: "locandina"),
                     Film (titolo: "dd", descrizione: "e", locandina: "locandina"),*/
                     Film (titolo: "The Suicide Squad", descrizione: "Supervillains Harley Quinn, Bloodsport, Peacemaker and a collection of nutty cons at Belle Reve prison join the super-secret, super-shady Task Force X as they are dropped off at the remote, enemy-infused island of Corto Maltese.", locandina: "suicide squad"),
                     Film (titolo: "Zack Snyder's Justice League ", descrizione: " Determined to ensure Superman's ultimate sacrifice was not in vain, Bruce Wayne aligns forces with Diana Prince with plans to recruit a team of metahumans to protect the world from an approaching threat of catastrophic proportions.", locandina: "zack snyder"),
                     Film (titolo: "The Falcon and the Winter Soldier", descrizione: "Following the events of 'Avengers: Endgame,' Sam Wilson/Falcon and Bucky Barnes/Winter Soldier team up in a global adventure that tests their abilities -- and their patience.", locandina: "the falcon and the winter soldier"),
                     Film (titolo: "Mortal Kombat", descrizione: "MMA fighter Cole Young seeks out Earth's greatest champions in order to stand against the enemies of Outworld in a high stakes battle for the universe.", locandina: "mortal kombat"),
                     Film (titolo: "Wrath of Man", descrizione: "The plot follows H, a cold and mysterious character working at a cash truck company responsible for moving hundreds of millions of dollars around Los Angeles each week.", locandina: "wrath of men"),
                     Film (titolo: " WandaVision", descrizione: "Blends the style of classic sitcoms with the MCU, in which Wanda Maximoff and Vision - two super-powered beings living their ideal suburban lives - begin to suspect that everything is not as it seems.", locandina: "wanda vision"),
                     Film (titolo: "Justice League ", descrizione: "Fueled by his restored faith in humanity and inspired by Superman's selfless act, Bruce Wayne enlists the help of his new-found ally, Diana Prince, to face an even greater enemy.", locandina: "justice league"),
                     Film (titolo: "Godzilla II - King of the Monsters", descrizione: "The crypto-zoological agency Monarch faces off against a battery of god-sized monsters, including the mighty Godzilla, who collides with Mothra, Rodan, and his ultimate nemesis, the three-headed King Ghidorah.", locandina: "godzilla II"),
                     Film (titolo: "Raya e l'ultimo drago", descrizione: "In a realm known as Kumandra, a re-imagined Earth inhabited by an ancient civilization, a warrior named Raya is determined to find the last dragon.", locandina: "raya e l'ultimo drago"),
                     Film (titolo: "Wonder Woman 1984", descrizione: "Diana must contend with a work colleague and businessman, whose desire for extreme wealth sends the world down a path of destruction, after an ancient artifact that grants wishes goes missing.", locandina: "wonder woman 1984"),
                     Film (titolo: "Kong: Skull Island", descrizione: "After the Vietnam war, a team of scientists explores an uncharted island in the Pacific, venturing into the domain of the mighty Kong, and must fight to escape a primal Eden.", locandina: "kong- skull island"),
                    /* Film (titolo: "ii", descrizione: "e", locandina: "locandina"),
                     Film (titolo: "ii", descrizione: "e", locandina: "locandina"),
                     Film (titolo: "ii", descrizione: "e", locandina: "locandina"),
                     Film (titolo: "ii", descrizione: "e", locandina: "locandina"),
                     */
                     
]















var arrayNegativi = [
    Film (titolo: "ScaryMovie", descrizione: "scream ", locandina: "scarym"),
    Film (titolo: "MEET THE PARENTS ", descrizione: "Meeting your partner’s parents is bound to be stressful – but Greg Focker (Ben Stiller) has it worse than most. Turns out his potential father in law (Robert De Niro) is a former CIA agent with a suspicious nature – and a polygraph lie-detector machine at his disposal. Over the course of an eventful visit, Focker’s misfortune builds to a farcical crescendo as his intended (Teri Polo) looks on. Stiller is on hilarious, hapless form and De Niro has never been funnier. ", locandina: "meettheparent"),
    Film (titolo: "MEAN GIRLS", descrizione: "When Cady (Lindsay Lohan) moves from being home-schooled by her parents in Africa to an American high school, she has rude awakening. Confronted by the school's hierarchy where popularity means everything, she finds herself infiltrating the girl clique The Plastics. Loaded with laugh-out-loud moments, the script, penned by Tina Fey, is filled with zingers. It's a film that provides genuine insight and empathy as well as a hefty dose of putdowns and comeuppances.", locandina: "meangirls"),
    
    Film (titolo: "PULP FICTION", descrizione: "When Cady (Lindsay Lohan) moves from being home-schooled by her parents in Africa to an American high school, she has rude awakening. Confronted by the school's hierarchy where popularity means everything, she finds herself infiltrating the girl clique The Plastics. Loaded with laugh-out-loud moments, the script, penned by Tina Fey, is filled with zingers. It's a film that provides genuine insight and empathy as well as a hefty dose of putdowns and comeuppances.", locandina: "pulpfiction"),
    Film (titolo: "HOT FUZZ", descrizione: "When Cady (Lindsay Lohan) moves from being home-schooled by her parents in Africa to an American high school, she has rude awakening. Confronted by the school's hierarchy where popularity means everything, she finds herself infiltrating the girl clique The Plastics. Loaded with laugh-out-loud moments, the script, penned by Tina Fey, is filled with zingers. It's a film that provides genuine insight and empathy as well as a hefty dose of putdowns and comeuppances.", locandina: "hotfuzz"),
    Film (titolo: "SAFETY LAST!", descrizione: "Always sporting round specs and straw boater, silent comedian Harold Lloyd’s shtick was to cultivate a likeable boy-next-door persona, then put his protagonist in hair-raising jeopardy. In his best-known feature, his plan to get an athletic acquaintance to climb a department store facade as a publicity stunt backfires, so Harold tackles the perilous ascent himself. Cue pesky pigeons and an inconvenient clock face in a beautifully constructed, very funny set-piece whose clever use of perspective creates vertiginous thrills without back projection – or a single computer pixel!", locandina: "safetylast"),
    Film (titolo: "THE GRADUATE", descrizione: "It’s easy to forget that, in the pre-blockbuster days, ‘The Graduate’ was one of the biggest box-office smashes of all time (it’s still No 21, adjusted for inflation). So what was it about this intimate, simple drama – a film we’d now refer to as an indie, even though it was studio-made – that captured the public imagination? Quite simply, it was a matter of timing: here was a film that, with its depiction of bourgeois boredom, teenage angst and sexual liberation (not to mention those awesome Simon and Garfunkel songs) absolutely nailed the mood of the late 1960s. ", locandina: "thegraduate"),
    Film (titolo: "LOCAL HERO", descrizione: "If you’re ever suffering from chilly cockles, Bill Forsyth’s twinkly, good-hearted comedy will warm them right up – and in the wake of Donald Trump’s terrifying ascendance, it’s even more timely. Peter Riegert plays an American lawyer dispatched by his oil-baron boss to Scotland to secure the site for their next refinery. But whaddaya know – it’s right on top of a quaint little fishing village populated by wise, loveable Scotspersons. Epic adorable-ness ensues. ", locandina: "localhero"),
    Film (titolo: "PALM SPRINGS", descrizione: "We’re calling it: this time-loop romantic comedy is here to stay. Yes, it’s a Groundhog Day-inspired film about escaping the repetition of life that was released at a time when, well, you know... Yet Palm Springs is an absolute delight, a buddy comedy and rom-com twist on ‘one of those infinite time loop situations you might’ve heard about’ that stays refreshing thanks to the believably vulnerable chemistry between Andy Samberg and Cristin Milioti. That and the presence of a coked-up, crossbow-wielding JK Simmons. It’s sunny, sharp-witted, and, in it’s own way, oddly profound. ", locandina: "palmsprings"),
    Film (titolo: "SCHOOL OF ROCK", descrizione: "Jack Black is at his most endearing in this underdog story about a struggling musician who poses as a substituted teacher and ends up coaching a class if misfits to compete in a Battle of the Bands. Sure, it echoes 'Sister Act 2', but Richard Linklater's film pretty much defines the term 'ebullient'. It sails on a wave of pin-shap one-liners, constant heavy riffage and plucky performances from the young cast. ", locandina: "schoolofrock"),
    Film (titolo: "THE MASK", descrizione: "When The Mask first came out in 1994, reviewers raved about the ultra-modern special effects used to turn Jim Carrey into a living cartoon. While the CGI might not have stood the test of time, Carrey’s elastic performance as shy nice guy Stanley and his alter ego The Mask is just as enthralling. Jim’s Mask is a grotesque green-faced schmooze-ball with a passion for farting, cheesy chat-up lines and Cameron Diaz. And, most importantly, he’s sssssmokin’! ", locandina: "themask"),
    Film (titolo: "OLD SCHOOL ", descrizione: "Rebooting the frat comedy for the slightly-more-sensitive ’00s while keeping the band-of-misfits ethos intact, ‘Old School’ is basically ‘Animal House’ with a bigger heart and a few more grey hairs. The plot – grown-up dudes take a house near a university campus and decide, for reasons too convoluted to go into, to start their own fraternity – may be daft, but the superb script is matched by effortless performances: Will Ferrell’s Frank the Tank is a glorious creation. Oh, and the wedding band scene is genius, pure and simple.", locandina: "oldschool"),
    Film (titolo: "SLAP SHOT", descrizione: "Rebooting the frat comedy for the slightly-more-sensitive ’00s while keeping the band-of-misfits ethos intact, ‘Old School’ is basically ‘Animal House’ with a bigger heart and a few more grey hairs. The plot – grown-up dudes take a house near a university campus and decide, for reasons too convoluted to go into, to start their own fraternity – may be daft, but the superb script is matched by effortless performances: Will Ferrell’s Frank the Tank is a glorious creation. Oh, and the wedding band scene is genius, pure and simple.", locandina: "slapshot"),
    Film (titolo: "TOY STORY", descrizione: "As the first Pixar animated feature film, 'Toy Story' set out the studio's M.O. perfectly: to make films that are just as entertaining for adults as they are for kids. Jokes and references that only grownups will 'get' elevates the story of the rivalry between toy cowboy Woody (voiced by Tom Hanks) and Buzz Lightyear (Tim Allen), the new toy on the block. It's the perfect combination of action and adventure that packs genuine heart and buckets of lols.", locandina: "toystory"),
    Film (titolo: "THE BLUE BROTHERS ", descrizione: "The controversy around ‘The Blues Brothers’ has been raging since its release. Is this a case of two white comedians exploiting the heroes of soul music to make themselves look cool? Or is the film actually a loving tribute to a great American art form? The truth is, a bit of both. But luckily, there’s a brilliantly paced plot, a punchy script and a riot of car chases to keep you distracted every time Belushi and Aykroyd’s mugging gets a bit much. Of course, the heart of the movie is in its musical performances: Cab Calloway, Ray Charles and James Brown all hit hard, but it’s Aretha Franklin’s ‘Respect’ that’ll have you jiving in your seat. ", locandina: "thebluebrothers"),
    Film (titolo: "NAPOLEON DYNAMITE ", descrizione: "The controversy around ‘The Blues Brothers’ has been raging since its release. Is this a case of two white comedians exploiting the heroes of soul music to make themselves look cool? Or is the film actually a loving tribute to a great American art form? The truth is, a bit of both. But luckily, there’s a brilliantly paced plot, a punchy script and a riot of car chases to keep you distracted every time Belushi and Aykroyd’s mugging gets a bit much. Of course, the heart of the movie is in its musical performances: Cab Calloway, Ray Charles and James Brown all hit hard, but it’s Aretha Franklin’s ‘Respect’ that’ll have you jiving in your seat. ", locandina: "napoleondynamite"),
    Film (titolo: "THE INTERN ", descrizione: "VINTAGE AND MODERN ARE MEETING AND THIS IS THE BEST COUPLE TO WORK! ", locandina: "theintern"),
    Film (titolo: "THE PINK PANTHER", descrizione: "The first in a series of five films featuring the clumsy antics of Peter Sellers’s bungling pseudo-French detective Chief Inspector Clouseau, ‘The Pink Panther’ is also the most measured, languorous and subtle of the lot. While often very funny, Sellers’s incompetent character only came to the fore from the second film, ‘A Shot in the Dark’, onwards. Consequently, anyone seeing this expecting wall-to-wall Sellers may be a mite disappointed. But hey, it knocks spots off the awful 2006 remake.", locandina: "pinkpanther"),
    Film (titolo: "ELF ", descrizione: "This story of Buddy the 'elf', a human raised in the north pole by Santa and his real elves, and his journey to find his real dad is fast becoming a festive family staple. The juxtaposition between Ferrell's Buddy, a guileless simpleton who accidentally causes havoc and destruction, and his stiff-lipped and gruff businessman of a father provides genuine moments of humour and heart. Meanwhile, director Jon Favreau delivers any cornball sentiments with an adept balance of irony and sincerity.  ", locandina: "elf"),
    Film (titolo: "GHOSTBUSTERS", descrizione: "When New York is invaded by ghastly ghouls, who you gonna call? You know the answer: four self-styled Ghostbusters ready to dash in and zap the spirits into oblivion. Much of this sci-fi-comedy’s charm lies in its have-a-go-heroes: these underdogs are thrown into the spotlight with delightful results. Bill Murray’s deadpan, womanising scientist is an undoubted highlight, while Rick Moranis brings crazy character humour as the dork living in the most haunted building in Manhattan.  ", locandina: "ghostbusters"),
    Film (titolo: "TRADING PLACE", descrizione: "When New York is invaded by ghastly ghouls, who you gonna call? You know the answer: four self-styled Ghostbusters ready to dash in and zap the spirits into oblivion. Much of this sci-fi-comedy’s charm lies in its have-a-go-heroes: these underdogs are thrown into the spotlight with delightful results. Bill Murray’s deadpan, womanising scientist is an undoubted highlight, while Rick Moranis brings crazy character humour as the dork living in the most haunted building in Manhattan.  ", locandina: "tradingplace"),
    Film (titolo: "Dumb&Dumber ", descrizione: "Imagine the contents of your hyperactive little brother’s brain splatted on to a TV screen and you have ‘Dumb & Dumber’. Jim Carrey and Jeff Daniels star as a pair of stupendously stupid no-hopers who head on a road trip across America to return a woman’s briefcase. Unapologetically gross-out, the movie’s a mulch of butt jokes, toilet jokes, snot jokes and sex jokes. It’s totally regressive but in a whoops-just-snorted-my-drink-everywhere-laughing kind of way.  ", locandina: "dumb&dumber"),
    Film (titolo: "Some like it hot", descrizione: "Jack Lemmon and Tony Curtis star as Jerry and Joe, two musicians who are forced to flee Chicago after witnessing the 1929 Valentine’s Day Massacre and disguise themselves as female members of a band travelling to Florida. Joe falls for the band’s seductive singer, Sugar (Marilyn Monroe), while Jerry has to fight off the lusty attentions of a wealthy old man. Billy Wilder delivers a pacy, racy cross-dressing farce, full of gags and sauce. ", locandina: "somelikeithot"),
    Film (titolo: "The big Lebowski", descrizione: "Imagine the contents of your hyperactive little brother’s brain splatted on to a TV screen and you have ‘Dumb & Dumber’. Jim Carrey and Jeff Daniels star as a pair of stupendously stupid no-hopers who head on a road trip across America to return a woman’s briefcase. Unapologetically gross-out, the movie’s a mulch of butt jokes, toilet jokes, snot jokes and sex jokes. It’s totally regressive but in a whoops-just-snorted-my-drink-everywhere-laughing kind of way. ", locandina: "thebiglebowski"),
    Film (titolo: "Team America: world police ", descrizione: "‘South Park’ creators Trey Parker and Matt Stone had no idea what they were taking on when they decided to make a ‘Thunderbirds’-style puppet movie about the War on Terror. A year of 20-hour days later – Stone described it as ‘the worst time of my life’ – the film was unleashed, and justified every minute of the duo’s hard work. As concerned with skewering the twin pomposities of mainstream action cinema and liberal Hollywood as it is with the terrorist armies of Durkadurkastan and North Korea, the film borders on genius in its self-aware use of wooden marionettes, particularly in the notorious sex scene. Even Matt Damon thinks it’s funny. ", locandina: "teamamerica"),
    Film (titolo: "Whitnail & Nail", descrizione: "The funniest parts of ‘Withnail & I’ are the early scenes, when, festering in a Camden flat resembling the inside of a cancerous lung, Withnail and Marwood stumble towards the end of an epic speed and booze bender. There are delirious flights of fancy, bouts of druggy nonsense (‘my thumbs have gone weird’), an abortive attempt to clean the kitchen and a cherishable visit from terrifying drug dealer Danny (Ralph Brown). Later, though, tragedy looms large – and Withnail’s despairing traipse through rain-sodden Regent’s Park ranks among the most heartbreaking closing scenes in all cinema.  ", locandina: "whitnail&nail"),
    Film (titolo: "  The Jerk", descrizione: "The funniest parts of ‘Withnail & I’ are the early scenes, when, festering in a Camden flat resembling the inside of a cancerous lung, Withnail and Marwood stumble towards the end of an epic speed and booze bender. There are delirious flights of fancy, bouts of druggy nonsense (‘my thumbs have gone weird’), an abortive attempt to clean the kitchen and a cherishable visit from terrifying drug dealer Danny (Ralph Brown). Later, though, tragedy looms large – and Withnail’s despairing traipse through rain-sodden Regent’s Park ranks among the most heartbreaking closing scenes in all cinema.  ", locandina: "thejerk"),
    Film (titolo: "Annie Hall", descrizione: " Is as Woody Allen as Woody Allen gets  hilarious, neurotic and occupied by the realisation that whatever happens, life is going to trample all over you. It’s also one of the greatest romantic comedies every made (with some of the funniest lines: ‘Don’t knock masturbation. It’s sex with someone I love’). Allen is Alvy Singer, who’s just split from scatty singer Annie (Diane Keaton, his real-life ex). What follows is an anatomy of their relationship. Allen has said that the film is not autobiographical  he co-wrote it with Marshall Brickman  but that’s not what we want to hear. CC ", locandina: "anniehall"),
    Film (titolo: "BRIDESSMAIDS", descrizione: "'Bridesmaids' is way more than just a lads comedy with the genders switched. Sure, there are some of the bad-taste trappings, but it more than outgrows them with its silly-but-smart script and the lively direction from 'Freaks and Geeks' legend Paul Feig. Even better, though, is the note-perfect casting. Kristen Wiig's performance as Annie is raucously hilarious (her impersonation of a penis is a highlight), as is Rose Byrne, whose deadpan performance as Helen is severely underrated. Mostly, though, it works because the relationships between the women feel real and honest. ", locandina: "bridessmaids"),
    Film (titolo: "PLAY IT AGAIN, SAM ", descrizione: "Woody Allen establishes his on-screen persona as a haplessly neurotic would-be lover in this sparkling adaptation of his 1969 Broadway play, where he’s a movie critic so obsessed by ‘Casablanca’ that he’s conjured up an imaginary Humphrey Bogart to dispense hard-boiled wisdom. Bogey’s kiss-or-kill strategies couldn’t be less appropriate, which is where the fun starts, and Diane Keaton makes a most appealing romantic foil as events head to a wittily achieved airport finale with deliciously misappropriated classic movie dialogue.", locandina: "playitagainsam"),
    Film (titolo: "THE HOLIDAY ", descrizione: "IT’S POSSIBLE TO MEET LOVE WHEREVER YOU GO! ", locandina: "Theholiday"),
    Film (titolo: "The Farewell", descrizione: "Because you'll be reminded of a simple fact that we all know, but usually try to ignore actively thinking about: Everyone we love will eventually die and all we can do is make the most of the time we have with them. ", locandina: "thefarewell"),
    Film (titolo: "Seven Pounds", descrizione: "We'll try to be as unspoilery as possible here, but let's just say that when the truth about the main character's random acts of kindness is revealed, crying is guaranteed. ", locandina: "sevenpounds"),
    Film (titolo: "Me before you", descrizione: "Not all love stories have a happy ending, but it's even sadder when that sad ending is part of a choice and not fate stepping in.  ", locandina: "mebeforeu"),
    Film (titolo: "Dead Poets Society", descrizione: "In this movie, we have: Robin Williams as the teacher figure you always wanted, a group of young men trying to find there way in this scary unknown world, overbearing parents who just won't quit meddling, and the lifealtering power of literature. ", locandina: "deadpoet"),
    Film (titolo: "Marriage story", descrizione: "We've all experienced the crushing loss of a relationship falling apart and Marriage Story reflects that pain right back to us. ", locandina: "marriage"),
    Film (titolo: "If beale street could talk", descrizione: "It tracks the life of possibly one of the cutest and most energetic dogs on the planet. It's promoted as a comedy, which, trust us, does have its moments, but like we said, 'tracks the life,' so uh, that also includes the end. ", locandina: "ifbeale"),
    Film (titolo: "The color purple", descrizione: "When things seem to be looking up for Celie (Whoopi Goldberg), things just go back down again, but the strength Celie possesses will keep you watching. BTW: The film, directed by Steven Spielberg, is based on the 1982 Pulitzer Prizewinning novel, The Color Purple by Alice Walker ", locandina: "purple"),
    Film (titolo: "A walk to remember ", descrizione: "In a twist of events, a high school girl doesn't want the popular guy to fall in love with her because she's secretly dying. Shocker alert: he doesn't listen to her pleas. Instead, he falls deeply in love with his shy classmate, and well you can guess what happens. ", locandina: "walk"),
    Film (titolo: "Sophie’s Choice", descrizione: "In a twist of events, a high school girl doesn't want the popular guy to fall in love with her because she's secretly dying. Shocker alert: he doesn't listen to her pleas. Instead, he falls deeply in love with his shy classmate, and well you can guess what happens.", locandina: "sophie"),
    Film (titolo: "Romeo+Juliet", descrizione: "In a twist of events, a high school girl doesn't want the popular guy to fall in love with her because she's secretly dying. Shocker alert: he doesn't listen to her pleas. Instead, he falls deeply in love with his shy classmate, and well you can guess what happens. ", locandina: "romeo"),
    Film (titolo: "Mary and Max", descrizione: "This movie captures the essence of intense loneliness, isolation, suicidal depression, and the power of a single, human connection in a way that no movie with live-action actors ever has. ", locandina: "mary"),
    Film (titolo: "AI: artificial intelligence", descrizione: "If you can watch the scene where Haley Joel Osment, playing a robot who believes he's a real boy, begs his human mother not to abandon him as she drives away and leaves him to mourn her love for all eternity, then you might be the robot. ", locandina: "ai"),
    Film (titolo: "The lion king", descrizione: "If you're a millennial, Mufasa's death scene will always take you right back to the first time you cried in a movie theater. ", locandina: "lion"),
    Film (titolo: "One day", descrizione: "One of the most manipulative movies of all time (in a good-cry way), this story that follows Anne Hathaway (with an accent) and Jim Sturgess as two people who meet in college and meet up again on the same day each year for two decades. There is more death than there probably needs to be for something that's such a slow burn. Even telling you the plot might make you tear up. ", locandina: "oned"),
    Film (titolo: "Never let me go", descrizione: "Swelling orchestral soundtrack? Check. Romantic, forbidden love triangle? Check. Doomed loves? Check. Postmodern fable about clones based on a book by Kishuo Ishiguro? Um, also check. ", locandina: "neverlet"),
    Film (titolo: "Finding Neverland", descrizione: "The true-ish story of Peter Pan creator J.M. Barrie and his friendship with a widow (Kate Winslet, again! She's on this list a lot.) and her four sons, who inspired the tale of the little boy who never grew up. ", locandina: "finding"),
    Film (titolo: "My sister’s keeper ", descrizione: "Abigail Breslin stars in this Nicholas Sparks movie based on a Jodi Picoult bestselling book. She plays a young woman genetically engineered from birth to provide bone marrow and various other donations for her terminally ill older sister, but who decides to legally emancipate herself from her parents and choose her own destiny—even at the risk of letting her sister die. ", locandina: "sister"),
    Film (titolo: "Lion ", descrizione: "The story of a little Indian boy who gets separated from his family, adopted by an Australian couple, and then who goes in search of his birth family. Ugh, it's so sad! ", locandina: "lion2"),
    Film (titolo: "The way we were", descrizione: "Barbra Streisand and Robert Redford have undeniable chemistry in this story of two mismatched lovers who, in the end, just can't make it work. It's sad because it'll remind you of your own lost loves. Also, it's got a killer soundtrack. ", locandina: "theway"),
    //sto a 20 di triste
    Film (titolo: "Moulin Rouge", descrizione: "fun, gorgeous, sexy, musical romp about love that ultimately ends in tuberculosis. So unfair. ", locandina: "moulin"),
    Film (titolo: "Atonement ", descrizione: "A beautiful, lush movie about a terrible mistake made by a young girl that ruins not only her life but the lives of two innocent, very attractive people? Ugh, fine, pass the tissues. ", locandina: "atonem"),
    Film (titolo: "UP", descrizione: "onestly, you can watch this movie and not cry, but it would require skipping the first 10 minutes. The gist is: Woman meets man, woman marries man, woman lives a perfect life with man, woman dies, man has to keep on going somehow. Even typing that made me well up. ", locandina: "up"),
    Film (titolo: "Steel Magnolias ", descrizione: "It's a movie about a group of sister-friends, one of whom dies tragically after having a kid against doctor's orders. If you have a pulse, you will cry. Also, Dolly Parton is in it. That's not a reason to cry but it's good to know. ", locandina: "magnolias"),
    Film (titolo: "My dog skip ", descrizione: "There should be a rule like Chekhov's Gun in movies, but it's Chekhov's Dog: If there's a dog in a heartwarming family film's first ten minutes, the dog is going to die by the end of the movie. Yes, the dog dies. I told you there were spoilers. ", locandina: "mydog"),
    Film (titolo: "My girl", descrizione: "There should be a rule like Chekhov's Gun in movies, but it's Chekhov's Dog: If there's a dog in a heartwarming family film's first ten minutes, the dog is going to die by the end of the movie. Yes, the dog dies. I told you there were spoilers. ", locandina: "mygirl"),
    Film (titolo: "The fault in our stars ", descrizione: "It's a love story that heavily involves cancer. Gee, wonder if you'll be sad about that? ", locandina: "fault"),
    Film (titolo: "Legends of the Fall", descrizione: "Legends of the Fall is an epic of gargantuan proportions, full of tender moments, broken hearts, unexpected deaths, and Brad Pitt's free-flowing mane of blonde hair. Its beauty alone will get you. ", locandina: "fall"),
    Film (titolo: "Hachiko", descrizione: "This heartwarming true story is an American adaptation of a Japanese tale about a loyal dog named Hachiko. This very special friend would accompany his master to the train station every day and return each afternoon to greet him. Sadly his master departs one day, passes away and never returns.", locandina: "haki"),
    Film (titolo: "Last of Mohicans", descrizione: "Legends of the Fall is an epic of gargantuan proportions, full of tender moments, broken hearts, unexpected deaths, and Brad Pitt's free-flowing mane of blonde hair. Its beauty alone will get you.", locandina: "moicans"),
   
    Film (titolo: "It Follows", descrizione: "Infection in horror movies is spread in many ways. A bite here, an injection of a transformational virus there. Hell, we’ve even had watching a video tape and having a ghost in real need of some conditioner come and get you seven days later. To add a new spin to things, the grim plodding nasty of It Follows comes to get you if you literally, well, do the nasty. While a 21st century horror about a sexually transmitted horrific curse sounds like it should be driven off a cliff, It Follows is a truly terrifying experience. The horror is real as teenager Jay is plagued by ghosts no one else can see, slowly, endlessly walking towards her unless she ‘passes it on’. Proving just how good Jay’s friends are, they club together to take on the supernatural entity.  ", locandina: "itfollows"), //16horror
     Film (titolo: "An American Warewolf in London", descrizione: "Infection in horror movies is spread in many ways. A bite here, an injection of a transformational virus there. Hell, we’ve even had watching a video tape and having a ghost in real need of some conditioner come and get you seven days later. To add a new spin to things, the grim plodding nasty of It Follows comes to get you if you literally, well, do the nasty. While a 21st century horror about a sexually transmitted horrific curse sounds like it should be driven off a cliff, It Follows is a truly terrifying experience. The horror is real as teenager Jay is plagued by ghosts no one else can see, slowly, endlessly walking towards her unless she ‘passes it on’. Proving just how good Jay’s friends are, they club together to take on the supernatural entity.  ", locandina: "anamericanwarewolfinlondon"),
     Film (titolo: "REC", descrizione: "First off, we’re going to pretend that the English language remake, Quarantine, doesn’t exist. Good. Now that’s out of the way, it’s time to wax lyrical about the true terror lurking inside a Barcelona apartment block in this Spanish scarefest. As with all the best found footage horror movies, the set-up here is very simple. The crew of a morning TV show is following a team of firefighters when a call comes in about a woman behaving strangely in her apartment. Of course, Angela and her cameraman Pablo excitedly follow the crew of emergency workers into, well, hell.    ", locandina: "rec"),
     Film (titolo: "The witch", descrizione: "Self described as a ‘New England folk tale’ - although it’s more like a fairy tale from hell - Robert Eggers’ terrifying period drama follows a Puritan family after they are ejected from their colony. Screaming ‘don’t do it’ at the screen just doesn’t work as William (Ralph Ineson) takes his wife Katherine (Kate Dickie) and his five children into the deep, dark woods to survive alone on a farm. It’s not spoiling anything to say that it doesn’t go particularly well. Following Thomasin, the eldest daughter of the family played by Anya Taylor Joy in her first credited role, we witness the tense unravelling of a dysfunctional family faced with the horrific prospect of an outside force staring out at them from the trees.  ", locandina: "thewitch"),
     Film (titolo: "The Blair Watch Project", descrizione: "Ever wondered why no-one’s out camping in the woods these days? It’s not that millennials really need to be within one hundred feet of a charging point at all times, it’s just the fact that a full generation of us saw The Blair Witch Project in our early teens and we just really like to sleep inside now. This, now almost mythical, found footage horror follows three young documentary makers as they journey to Burkittsville in Maryland. Heather, Mike, and Josh start off interviewing the locals about the local legend of The Blair Witch, a particularly nasty tale you’d hope was just to keep children eating their veggies, before heading into the woods where the witch apparently resides. Given that all that’s ever been found are these tapes, there's not exactly a happy ending. ", locandina: "theblairwatchproject"),
     Film (titolo: "THE WICKER MAN", descrizione: "If the above image doesn’t strike a sense of menace into your heart, it’s time to mainline Robin Hardy’s folk horror directly into your eyes. No, The Wicker Man isn’t just about reaction gifs and mocking the bee-packed Nicholas Cage remake. If nothing else, watching Edward Woodward’s journey to Summerisle is essential background reading for the 21st century spate of rural scary movies. The ideal accompaniment for the modern nastiness of Ari Aster’s Midsommar or Ben Wheatley’s Kill List, The Wickerman’s appeal is in its sheer terrifying simplicity. Policeman goes to island on the hunt for a missing girl. Policeman discovers all is not what it seems. Oh, and indeed, dear.   ", locandina: "thewickerman"),
     Film (titolo: "The Shining", descrizione: "Even if you haven’t watched Stanley Kubrick’s masterpiece, you’ll know of The Shining. You’ll know Jack Nicholson’s (apparently ad-libbed) “Heeeeeeeere’s Johnny” and you might even be aware that if you’re handed the keys to room 237 in a hotel, you might want to switch it for another suite. But what if you haven’t? What if you have been snowed up in a mysterious hotel with only hedge animals for company? Well, The Shining follows a man and his family as he takes on the role of winter caretaker at a resort hotel known as The Overlook. Given that this is a Stephen King adaptation (albeit one that that horror author hates so much that he made his own movie), the winter months don’t go well. The Overlook Hotel, it turns out, doesn’t really like people. ", locandina: "theshining"),
     Film (titolo: "Get Out", descrizione: "Mid-20's photographer Chris is driving out to rural New York to meet his girlfriend's parents for the first time, but he's a little nervous. 'Do they know I'm black?' he tentatively asks Rose, but she's having none of it: 'My Dad would have voted for Obama a third time if he could have!'. Phew! What could possibly go wrong? Everything. Everything can go wrong, Chris. Turn back now. This isn't just going to be slightly socially awkward.  ", locandina: "getout"),
     Film (titolo: "28 Days Later", descrizione: "Let’s get the undead elephant out of the room first. Danny Boyle’s horror is a zombie movie. Yes, they can run, but it’s important to think of this horrible lot as part of the same family tree as Romero’s finest. Maybe they wouldn’t have Christmas dinner together but they’d at least send cards and maybe some gift cards for the necrotic kids. The important thing is, regardless of their speed, these zombies are still the destroyers of worlds. When Jim (Cillian Murphy) wakes up in a hospital bed - a lot like our friend Karl in The Walking Dead - he staggers out into an apocalyptic London that will never be the same again.  ", locandina: "28dayslater"),
     Film (titolo: "Scream", descrizione: "By the late '90s, horror was looking a little tired. The masked slasher trope was staggering along in a dire need of a cup of very strong espresso. What it got instead was Wes Craven’s Scream which, despite being parodied into Inception levels of postmodern irony since, reinvigorated the genre with its perfect blend of knowing comedy and scares. Neve Campbell, Rose McGowan, and Drew Barrymore as teenagers talking fluent horror movie while being picked off by a genre-obsessed serial killer? Oh go on… Add in Courtney Cox - at the giddy heights of Friends fame - as intrepid news reporter Gale Weathers and Scream is a modern horror classic. ", locandina: "scream"),
     Film (titolo: "Alien", descrizione: "Arguably one of the greatest science fiction movies ever made also just happens to be one of the greatest horror movies too. It doesn't seem fair, does it? The original Alien from Ridley Scott sends the crew of the Nostromo to investigate a distress call from an abandoned alien spaceship as innocently as any gang of hormonal teenagers headed off to a remote cabin in the woods. And, just like those teenagers, not many of them are going to survive to tell the tale. Sigourney Weaver makes for the ultimate Final Girl here.  ", locandina: "alien"),
     Film (titolo: "Jaws", descrizione: "Before Jurassic Park, before ET, and an eternity before the majority of the cast of Ready Player One were brought screaming into existence, there was Jaws, Steven Spielberg’s toothy horror. And yes, this is a horror movie. Jaws, one of the original blockbusters on account of the number of people literally queuing around the block only to flee the cinema in terror, is horrifying. It doesn’t matter that the shark looks a little ropey now when he gets up close and personal, the story of Amity Island’s gory summer season as Chief Brody desperately tries to keep swimmers out of the water is the stuff of horror legend. And, let’s face it, you’re already humming the score.     ", locandina: "jaws"),
     Film (titolo: "Halloween", descrizione: "Who'd have thought an old Star Trek mask could be so terrifying? Director John Carpenter created a modern classic when he gave his villain a blank William Shatner mask to wear while he stalks babysitters around the fictional town of Haddonfield, Illinois. The movie created another icon, too, in Jamie-Leigh Curtis, who'd become both a scream queen in her own right, and the template for all final girls to follow. Who cares if the first scene makes no sense? This is a movie that starts with a child murdering his sister while wearing a clown mask and if that's not scary, you need your horror fan status revoked immediately. ", locandina: "halloween"),
     Film (titolo: "The Exorcist", descrizione: "And here we are into the top five of this best horror movies list. It almost feels predictable now that William Friedkin’s masterpiece, now in its 40s, is still looming near the top of so many horror features. But watch The Exorcist and you’ll understand why. This is the tale of Regan, the daughter of a successful movie actress who one day occupies herself in the basement by playing with a ouija board. If you have ever wondered why your parents don’t want you playing with this innocuous looking toy, a young Linda Blair probably has something to do with it. Using the ouija board as gateway, an unwelcome guest takes root in the little girl and the rest, as the titular exorcist arrives, is cinema history.  ", locandina: "theexorcist"),
    Film (titolo: "BLAZING SADDLES", descrizione: "‘My movies rise below vulgarity,’ Mel Brooks once quipped in the salad days of his career. Exhibit A for that claim, surely, is ‘Blazing Saddles’. A satire of Hollywood’s white-centric accounts of the American West, and told from the perspective of the first black sheriff in an all-white town, the film can be wince-inducing in the politically-charged, highly racial tone of its humour. Co-written by Richard Pryor (and co-starring Gene Wilder), it remains a riot of bad taste. John Wayne was offered a cameo role, Brooks once claimed in an interview. After reading and considering the script, the iconic Cowboy declined the opportunity. The dialogue, he said was ‘too dirty’. Amen to that. ", locandina: "blazing saddles "),

    Film (titolo: "Hereditary", descrizione: "Home is where the heart is. It’s also where the worst horror lives, hiding just beneath the surface of the perfect family life. A harrowed Toni Collette leads Ari Aster’s very first (!) feature film as the mother of a grieving family. The death of her own mother has sent shockwaves through their home and, to keep this review spoiler free, the future isn’t looking exactly, errr, bright either.", locandina: "hereditary"),
    Film (titolo: "CRAZY RICH ASIANS", descrizione: "Crazy Rich Asians was long overdue—a film that both sheds light on heritage while also telling a very entertaining romantic story. And even if you’re not the most inclined to watch a romcom, the movie’s incredible scenery alone is worth watching for. ", locandina: "crazy rich asians"),
    Film (titolo: "When Harry met Sally", descrizione: "It is perhaps the romantic comedy that stands above all others. Set across the expanse of multiple years, Harry and Sally were clearly always supposed to end up together. It just took a minute for it to happen. ", locandina: "when Harry met Sally"),
    Film (titolo: "Jaery Maguire", descrizione: "It is perhaps the romantic comedy that stands above all others. Set across the expanse of multiple years, Harry and Sally were clearly always supposed to end up together. It just took a minute for it to happen. ", locandina: "jerry maguire"),
    Film (titolo: "NOTTING HILL", descrizione: "A romance movie list without Julia Roberts is asinine. While it might be easy to fall back on Pretty Woman, the nuanced and sometimes unbelievable story between a commoner and a movie starlet is near the top of Roberts’s heap of films. ", locandina: "notting hill"),
    Film (titolo: "THE NOTEBOOK", descrizione: "Read me this story, and I’ll find you. Damn. Nicholas Sparks is cheesy and oftentimes over the top, but The Notebook is a romantic story of love that just beautiful enough that it transcends all of the cheesiness it takes to tell it.", locandina: "the notebook"),
    Film (titolo: "WEST SIDE STORY", descrizione: "It’s the quintessential movie musical, but it’s also still unfortunately relevant for our times. Two teens, torn apart by their attachment to rival gangs, fall in love for it all to end in tragedy. The film is currently being remade, but it’s hard to beat the original. ", locandina: "west side story"),
    Film (titolo: "GHOST", descrizione: "This is the only time a pottery wheel will ever be sexy. Thanks Patrick and Demi. ", locandina: "ghost"),
    Film (titolo: "CASABLANCA", descrizione: "This is the only time a pottery wheel will ever be sexy. Thanks Patrick and Demi. ", locandina: "casablanca"),
    Film (titolo: "HER", descrizione: "A film about teen pregnancy shouldn’t be able to be as romantic as Juno ended up being, but there’s something about love blossoming between friends who literally screwed themselves into a predicament that’s incredibly sweet and relatable. ", locandina: "her"),
    Film (titolo: "JUNO", descrizione: "A film about teen pregnancy shouldn’t be able to be as romantic as Juno ended up being, but there’s something about love blossoming between friends who literally screwed themselves into a predicament that’s incredibly sweet and relatable.", locandina: "juno"),
    Film (titolo: "MY “BEST FRIEND’S WEDDING", descrizione: "'You’re never gonna be jello.' The '90s classic is a romance that focuses a little more on what it means to be in love and a little less on the endgame. It’s also a good reminder to check yourself in the dating process: you might be chasing her, but who’s chasing you? ", locandina: "my best friend's wedding"),
    Film (titolo: "BULL DURHAM", descrizione: "The premise of Bull Durham is weird: Susan Sarandon plays a baseball-loving minor league groupie. Kevin Costner plays a veteran baseball player. The premise doesn’t sound super promising, but the delivery is outstanding. ", locandina: "bull durham"),
    Film (titolo: "Crazy, stupid, love", descrizione: "Crazy, Stupid, Love came out in the era when ensemble romantic movies were trying their damnedest to be a thing. Of all of them though, the Steve Carrell-led comedy might have gotten the closest. It’s extremely easy to watch, and if you’re not invested in one of the stories, don’t worry: there’s at least two more to watch. ", locandina: "crazy,stupid love"),
    Film (titolo: "A star is born", descrizione: "At first, it seems a little preemptive to put a movie released three months ago into the most romantic films category, but when you account for the fact that it’s been made a total of four times, it’s not hard to justify its status as a romantic must-watch. ", locandina: "a star is born"),
    
    Film (titolo: "Godzilla ", descrizione: "The world is beset by the appearance of monstrous creatures, but one of them may be the only one who can save humanity.", locandina: "godzilla"),
    Film (titolo: "Avengers: Endgame", descrizione: "After the devastating events of Avengers: Infinity War (2018), the universe is in ruins. With the help of remaining allies, the Avengers assemble once more in order to reverse Thanos' actions and restore balance to the universe.", locandina: "avengers- endgame"),
    Film (titolo: "Tenet", descrizione: "Armed with only one word, Tenet, and fighting for the survival of the entire world, a Protagonist journeys through a twilight world of international espionage on a mission that will unfold in something beyond real time.", locandina: "tenet"),
    Film (titolo: "Suicide Squad", descrizione: "A secret government agency recruits some of the most dangerous incarcerated super-villains to form a defensive task force. Their first mission: save the world from the apocalypse.", locandina: "suicide squad"),
    Film (titolo: "Notizie dal mondo", descrizione: "A Civil War veteran agrees to deliver a girl, taken by the Kiowa people years ago, to her aunt and uncle, against her will. They travel hundreds of miles and face grave dangers as they search for a place that either can call home.", locandina: "notizie dal mondo"),
    Film (titolo: "Batman v Superman: Dawn of Justice ", descrizione: "Fearing that the actions of Superman are left unchecked, Batman takes on the Man of Steel, while the world wrestles with what kind of a hero it really needs.", locandina: "batman v superman"),
    Film (titolo: " Way Down", descrizione: "Thom, a genius engineering graduate is interested in the Bank of Spain's safe. The Bank building is more than 100 years old, with no building blueprints available and a security system that includes an underground river that will flood the safe room if their walls are breached. As soon as Thom learns that a legendary lost treasure is going to be held at the bank's safe for just 10 days, he devises, together with charismatic art dealer Walter 'Cunningham' a detailed plan to breaking in. They will only have 105 minutes to do so, while the Bank's staff will be distracted, watching the 2010 Football World Cup final match , played by Spain's national football team and broadcast on a giant screen, coincidentally placed just in front of the Bank of Spain building.", locandina: "way down"),
    Film (titolo: "Honest Thief", descrizione: "Wanting to lead an honest life, a notorious bank robber turns himself in, only to be double-crossed by two ruthless FBI agents.", locandina: "honest thief"),
    Film (titolo: "L'uomo d'acciaio ", descrizione: "An alien child is evacuated from his dying world and sent to Earth to live among humans. His peace is threatened, when other survivors of his home planet invade Earth.", locandina: "l'uomo d'acciaio"),
    Film (titolo: "Il cavaliere oscuro", descrizione: "When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.", locandina: "il cavaliere oscuro"),
    Film (titolo: "The Equalizer", descrizione: "An enigmatic figure who uses her extensive skills to help those with nowhere else to turn.", locandina: "equaliz"),
    Film (titolo: "Inception ", descrizione: "A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.", locandina: "inception"),
    Film (titolo: "Jurassic Park", descrizione: "A pragmatic paleontologist visiting an almost complete theme park is tasked with protecting a couple of kids after a power failure causes the park's cloned dinosaurs to run loose.", locandina: "jurassic park"),
    Film (titolo: "Matrix", descrizione: "When a beautiful stranger leads computer hacker Neo to a forbidding underworld, he discovers the shocking truth--the life he knows is the elaborate deception of an evil cyber-intelligence.", locandina: "matrix"),
    Film (titolo: "Scott Pilgrim vs. the World ", descrizione: "In a magically realistic version of Toronto, a young man must defeat his new girlfriend's seven evil exes one by one in order to win her heart.", locandina: "scott pilgrim"),
    Film (titolo: "Enola Holmes", descrizione: "When Enola Holmes-Sherlock's teen sister-discovers her mother missing, she sets off to find her, becoming a super-sleuth in her own right as she outwits her famous brother and unravels a dangerous conspiracy around a mysterious young Lord.", locandina: "enola holmes"),
    Film (titolo: "Jack Ryan ", descrizione: "An up-and-coming CIA analyst, Jack Ryan, is thrust into a dangerous field assignment as he uncovers a pattern in terrorist communication that launches him into the center of a dangerous gambit.", locandina: "jack ryan"),
    Film (titolo: "Mulan ", descrizione: "A young Chinese maiden disguises herself as a male warrior in order to save her father", locandina: "mulan"),

]











var arrayNeutri   = [Film (titolo: "Host", descrizione: "We knew it was on the way, but post-pandemic horror has already arrived in the shape of a Zoom call gone very, very wrong. Desperately on the hunt for something to do other than endless lockdown quizzes – we feel this – a group of friends get together for an online mid-lockdown seance. What follows is a short, sharp shock of found footage adrenaline in an intimidatingly lean 56 minute run time. Host isn’t the first horror to take place on a computer screen, taking terrifying inspiration from REC, The Blair Witch Project, and Paranormal Activity, yet delivering a dangerously relevant frightmare. Happy spookies.", locandina: "locandina"),
                     Film (titolo: "Saw", descrizione: "It might have reignited the so-called torture porn genre with its (mostly) truly disgusting sequels but - and this is a huge ‘but’ - the original Saw is nowhere near as gross-gusting as you think it is and happens to be brilliant horror. Yes, the title is about an implement that a depraved killer suggests someone takes their leg off with rather than use a key to unlock a cuff, but Saw is actually remarkably restrained. The ideas at work here are significantly more grisly in your own mind than what you see on screen. Made on a shoestring budget by Leigh Whannell and James Wan, this tale of two men waking up in a bathroom, a corpse between them, is twisted but constantly intriguing. ", locandina: "saw"),
                     Film (titolo: "The thing ", descrizione: "Perhaps you’ve been buried in snow and have missed John Carpenter’s ultimate creature feature. Entirely understandable. Why don’t you come closer to the fire and defrost? The title might sound hokey but The Thing remains one of the most gloriously splattery and tense horrors of all time as a group of Americans at an Antarctic research station - including Kurt Russell’s R.J MacReady - take on an alien, well, thing that infects blood. It might start off taking out the canine companions - there’s no need to check out DoesTheDogDie.com this time around - but it really doesn’t stop there.", locandina: "thething"),
                     Film (titolo: "The birds ", descrizione: "Sure, there’s all that talk about showers and murder - Editor’s note: we know it’s not just ‘talk’ and Hitchcock’s Psycho is a genuine horror masterpiece - but it’s time to talk about the feathery elephant in the room. The Birds, the Master of Suspense’s loose adaptation of a short story of the same name by Daphne du Maurier, is scare cinema at its finest. When Tippi Hedren’s Melanie Daniels heads to Bodega Bay to deliver some love birds, she gets far more than she bargained for when the wild winged inhabitants of the town decide that human eyes might taste just as good as discarded chips. ", locandina: "thebirds"),
                     Film (titolo: "Shaun of the Dead", descrizione: "Choosing only one undead Romero offering for a list of the best horror Geymovies of all time is a bit like taking on the shuffling horde with a letter opener: gory and challenging, but not altogether impossible. After much deliberation then, it’s time to go shopping. Romero’s gory attack on the consumerist American dream follows four survivors of the zombie apocalypse as they arrive at a sprawling mall. While they manage to get inside without anything munching on their brains, it doesn’t take long before the beacon of the mall attracts other guests and the defences start to gorily break down.  ", locandina: "shunofdead"),
                     Film (titolo: "Dawn of the Dead", descrizione: "Choosing only one undead Romero offering for a list of the best horror movies of all time is a bit like taking on the shuffling horde with a letter opener: gory and challenging, but not altogether impossible. After much deliberation then, it’s time to go shopping. Romero’s gory attack on the consumerist American dream follows four survivors of the zombie apocalypse as they arrive at a sprawling mall. While they manage to get inside without anything munching on their brains, it doesn’t take long before the beacon of the mall attracts other guests and the defences start to gorily break down.  ", locandina: "dawnofdead"),
                   /*  Film (titolo: "ii", descrizione: "e", locandina: "locandina"),
                     Film (titolo: "ii", descrizione: "e", locandina: "locandina"),
                     Film (titolo: "ii", descrizione: "e", locandina: "locandina"),
                     Film (titolo: "ii", descrizione: "e", locandina: "locandina"),
                     Film (titolo: "ii", descrizione: "e", locandina: "locandina"),
                     Film (titolo: "ii", descrizione: "e", locandina: "locandina"),
                     Film (titolo: "ii", descrizione: "e", locandina: "locandina"),
                     Film (titolo: "ii", descrizione: "e", locandina: "locandina"),
                     Film (titolo: "ii", descrizione: "e", locandina: "locandina"),
                     Film (titolo: "ii", descrizione: "e", locandina: "locandina"),
                     Film (titolo: "ii", descrizione: "e", locandina: "locandina"),
 */
                     Film (titolo: "Legends of the Fall", descrizione: "Legends of the Fall is an epic of gargantuan proportions, full of tender moments, broken hearts, unexpected deaths, and Brad Pitt's free-flowing mane of blonde hair. Its beauty alone will get you. ", locandina: "fall"),
                     Film (titolo: "Hachiko", descrizione: "This heartwarming true story is an American adaptation of a Japanese tale about a loyal dog named Hachiko. This very special friend would accompany his master to the train station every day and return each afternoon to greet him. Sadly his master departs one day, passes away and never returns.", locandina: "haki"),
                     Film (titolo: "Last of Mohicans", descrizione: "Legends of the Fall is an epic of gargantuan proportions, full of tender moments, broken hearts, unexpected deaths, and Brad Pitt's free-flowing mane of blonde hair. Its beauty alone will get you.", locandina: "moicans"),
                     Film (titolo: "Mary and Max", descrizione: "This movie captures the essence of intense loneliness, isolation, suicidal depression, and the power of a single, human connection in a way that no movie with live-action actors ever has. ", locandina: "mary"),
                     Film (titolo: "AI: artificial intelligence", descrizione: "If you can watch the scene where Haley Joel Osment, playing a robot who believes he's a real boy, begs his human mother not to abandon him as she drives away and leaves him to mourn her love for all eternity, then you might be the robot. ", locandina: "ai"),
                     Film (titolo: "The lion king", descrizione: "If you're a millennial, Mufasa's death scene will always take you right back to the first time you cried in a movie theater. ", locandina: "lion"),
                     Film (titolo: "One day", descrizione: "One of the most manipulative movies of all time (in a good-cry way), this story that follows Anne Hathaway (with an accent) and Jim Sturgess as two people who meet in college and meet up again on the same day each year for two decades. There is more death than there probably needs to be for something that's such a slow burn. Even telling you the plot might make you tear up. ", locandina: "oned"),
                     Film (titolo: "Never let me go", descrizione: "Swelling orchestral soundtrack? Check. Romantic, forbidden love triangle? Check. Doomed loves? Check. Postmodern fable about clones based on a book by Kishuo Ishiguro? Um, also check. ", locandina: "neverlet"),
                     Film (titolo: "Finding Neverland", descrizione: "The true-ish story of Peter Pan creator J.M. Barrie and his friendship with a widow (Kate Winslet, again! She's on this list a lot.) and her four sons, who inspired the tale of the little boy who never grew up. ", locandina: "finding"),
                     Film (titolo: "My sister’s keeper ", descrizione: "Abigail Breslin stars in this Nicholas Sparks movie based on a Jodi Picoult bestselling book. She plays a young woman genetically engineered from birth to provide bone marrow and various other donations for her terminally ill older sister, but who decides to legally emancipate herself from her parents and choose her own destiny—even at the risk of letting her sister die. ", locandina: "sister"),
                     Film (titolo: "Lion ", descrizione: "The story of a little Indian boy who gets separated from his family, adopted by an Australian couple, and then who goes in search of his birth family. Ugh, it's so sad! ", locandina: "lion2"),
                     Film (titolo: "The way we were", descrizione: "Barbra Streisand and Robert Redford have undeniable chemistry in this story of two mismatched lovers who, in the end, just can't make it work. It's sad because it'll remind you of your own lost loves. Also, it's got a killer soundtrack. ", locandina: "theway"),
                     //sto a 20 di triste
                     Film (titolo: "Moulin Rouge", descrizione: "fun, gorgeous, sexy, musical romp about love that ultimately ends in tuberculosis. So unfair. ", locandina: "moulin"),
                     Film (titolo: "Atonement ", descrizione: "A beautiful, lush movie about a terrible mistake made by a young girl that ruins not only her life but the lives of two innocent, very attractive people? Ugh, fine, pass the tissues. ", locandina: "atonem"),
                     Film (titolo: "UP", descrizione: "onestly, you can watch this movie and not cry, but it would require skipping the first 10 minutes. The gist is: Woman meets man, woman marries man, woman lives a perfect life with man, woman dies, man has to keep on going somehow. Even typing that made me well up. ", locandina: "up"),
                     Film (titolo: "Steel Magnolias ", descrizione: "It's a movie about a group of sister-friends, one of whom dies tragically after having a kid against doctor's orders. If you have a pulse, you will cry. Also, Dolly Parton is in it. That's not a reason to cry but it's good to know. ", locandina: "magnolias"),
                     Film (titolo: "My dog skip ", descrizione: "There should be a rule like Chekhov's Gun in movies, but it's Chekhov's Dog: If there's a dog in a heartwarming family film's first ten minutes, the dog is going to die by the end of the movie. Yes, the dog dies. I told you there were spoilers. ", locandina: "mydog"),
                     Film (titolo: "My girl", descrizione: "There should be a rule like Chekhov's Gun in movies, but it's Chekhov's Dog: If there's a dog in a heartwarming family film's first ten minutes, the dog is going to die by the end of the movie. Yes, the dog dies. I told you there were spoilers. ", locandina: "mygirl"),
                     Film (titolo: "The fault in our stars ", descrizione: "It's a love story that heavily involves cancer. Gee, wonder if you'll be sad about that? ", locandina: "fault"),
                     Film (titolo: "Legends of the Fall", descrizione: "Legends of the Fall is an epic of gargantuan proportions, full of tender moments, broken hearts, unexpected deaths, and Brad Pitt's free-flowing mane of blonde hair. Its beauty alone will get you. ", locandina: "fall"),
                     Film (titolo: "Hachiko", descrizione: "This heartwarming true story is an American adaptation of a Japanese tale about a loyal dog named Hachiko. This very special friend would accompany his master to the train station every day and return each afternoon to greet him. Sadly his master departs one day, passes away and never returns.", locandina: "haki"),
                     Film (titolo: "Last of Mohicans", descrizione: "Legends of the Fall is an epic of gargantuan proportions, full of tender moments, broken hearts, unexpected deaths, and Brad Pitt's free-flowing mane of blonde hair. Its beauty alone will get you.", locandina: "moicans"),
                     Film (titolo: "Because I said so", descrizione: "Anyone with a meddling mom will relate to this movie about what happens when a mother tries to get involved in her daughter's dating life. Naturally, the outcome is hilarious—and very heartwarming.", locandina: "becauseisaidso"),
                     Film (titolo: "Forrest Gump", descrizione: "It's impossible not to feel inspired by the childlike optimism that guides Forrest through his life. Plus, you'll enjoy plenty of laughs along the way!", locandina: "forrestgump"),
                     Film (titolo: "Pitch Perfect", descrizione: "This outrageous, star-studded comedy will have you singing in the shower for days after the credits roll.", locandina: "pitchperfect"),
                     Film (titolo: "Matilda ", descrizione: "Matilda is an ordinary girl with a fairy-tale talent, and her exciting adventures teach a powerful lesson.", locandina: "matilda"),
                     Film (titolo: "Just go with it ", descrizione: "This hilarious rom-com shows what happens when a man fakes a family to avoid commitment—but ends up finding true love anyway.", locandina: "justgowithit"),
                     Film (titolo: "13 going on 30", descrizione: "Adults and kids alike will fall in love with this coming-of-age tale about a young teenager who learns the hard way what it's really like to grow up. ", locandina: "13goingon30"),
                     Film (titolo: "Love actually", descrizione: "Whether you're gearing up for the holidays or relaxing on summer vacation, there's never a bad time to watch this charming classic. ", locandina: "love actually"),
                     Film (titolo: "Zootopia ", descrizione: "Officer Judy Hopps is determined to crack a case in the all-animal city of Zootopia—even if it means partnering with a sly criminal. ", locandina: "zootopia "),
                     Film (titolo: "Frozen", descrizione: "There's a reason kids and adults are equally obsessed with this Disney cartoon. Make like Elsa and 'let it go!' ", locandina: "frozen"),
                     Film (titolo: "Ferris Bueller's Day Off", descrizione: "Revisit your teenage years and watch this John Hughes film while playing hooky from work. Just make sure your boss doesn't catch you!", locandina: "Ferris_Bueller's_Day_Off"),
                     Film (titolo: "The Blind Side", descrizione: "Real-life stories of sports heroes always leave you feeling like you can accomplish anything, and The Blind Side is no exception. ", locandina: "theblindside"),
                     Film (titolo: "Along come Polly", descrizione: "Reuben has always played it safe—until Polly came along. Prepare to LOL as you watch him try to keep up with her crazy antics! ", locandina: "alongcomepolly_"),
                     Film (titolo: "Mrs.Doubtfire", descrizione: "An eccentric father poses as Mrs. Doubtfire, a beloved British nanny, for a chance to spend more time with his kids. His plan ultimately gets derailed—but maybe it's for the best. ", locandina: "Mrs_Doubtfire"),
                     Film (titolo: "The Parent Trap", descrizione: "Double the daughters, double the smiles. Find out what happens when identical twins switch places and trick their parents. ", locandina: "the parent trap"),
                     Film (titolo: "Grease ", descrizione: "This movie is the one that you want! Every line and lyric in this 1978 classic is more quotable than the next—so prepare to sing along. ", locandina: "locandina_grease"),
                     Film (titolo: "Wall-E", descrizione: "WALL-E, short for Waste Allocation Load Lifter Earth-class, is the last robot left on the planet. That is, until he meets EVE—and his whole life changes. ", locandina: "walle"),
                     Film (titolo: "Wedding Crashers ", descrizione: "Leave it to a couple of lonely divorce attorneys to figure out a systematic way to pick up women at weddings. They have it down to a science—until they actually fall in love.", locandina: "weddingcrashers"),
                     Film (titolo: "The bucket list ", descrizione: "Leave it to a couple of lonely divorce attorneys to figure out a systematic way to pick up women at weddings. They have it down to a science—until they actually fall in love. ", locandina: "bucketlist"),
                     Film (titolo: "Good will hunting", descrizione: "A young man with a gift for mathematics can solve any equation, but can't figure out the direction of his own life. Then he meets an unorthodox psychologist who changes everything. ", locandina: "goodwillhunting"),
                     Film (titolo: "The Help", descrizione: "While this novel-based movie tackles the heavy topics of racism and segregation, the main characters will bring you nothing but smiles. ", locandina: "thehelp"),
                     Film (titolo: "Mamma Mia !", descrizione: "Have the time of your life watching this all-star cast act out a celebration of family, friends, and love.", locandina: "mammamia"),
                     Film (titolo: "Legally Blonde ", descrizione: "lle Woods will teach you how to 'bend and snap,' but more importantly, she'll remind you to never judge a book by its (pink) cover. ", locandina: "legallyblonde"),
]
